### PR TITLE
Updated batch template and incorporated csv read feature

### PR DESCRIPTION
**Pull request by coverney**

### CODE REVIEW

**Comment by coverney** [comment]
Once the other pull request get approved, then I will merge this branch with master and the tests should pass

**Comment by coverney** [comment]
Note: before we merge this with master, I would like to manually test the csv and original interfaces.

**Comment by jakebeal** [comment]
OK; let me know when you are ready for review and merge.

**Comment by coverney** [comment]
I am still in Boston waiting for traffic to die down, but I will hopefully test everything in the near future.

**Comment by coverney** [comment]
I just finished testing the interfaces.

**Pull request merged**
