### PR TITLE
Updated tutorial JSON Header

### PR DESCRIPTION
**Pull request by coverney**
Currently, the tests will not work because it requires the updated code within the 410 branch in TASBE. However, the 410 branch in TASBE needs the updated header JSON file, so would we be able to fulfill this pull request so we can completely test the 410 branch?

### CODE REVIEW

**Comment by coverney** [comment]
I meant the branch for issue 415

**Comment by coverney** [comment]
I just temporarily changed the travis.yml file, so I can run the tests. I will change it back once the tests pass.

**Comment by jakebeal** [comment]
Why have all of the point cloud files changed? This seems like it should not have happened?

**Comment by coverney** [comment]
They changed because the units changed from ERF to MEFL so I had to change the column names from channelName_ERF to channelName_MEFL

**Comment by jakebeal** [comment]
I think that should have changed only the first line of each file, however, and the diff is saying that every single line has changed.

**Pull request merged**
